#!/bin/bash
# ========================================== #
# BASH ALIASES & FUNCTIONS
# ========================================== #
# aliases cause you're a lazy piece of shit smfh

# ------------------------------------------
# Functions (Aliasing with Arguments)
# ------------------------------------------
mkcd() {
    mkdir -p "$1" && cd "$1" || return
}

# ------------------------------------------
# Safety & Administrative
# ------------------------------------------

# Escalation & Updates
if (( EUID != 0 )); then
    alias reboot='sudo reboot'
    # Detect package manager
    if command -v apt-get &>/dev/null; then
        alias update='sudo apt-get update && sudo apt-get upgrade'
    elif command -v pacman &>/dev/null; then
        alias update='sudo pacman -Syu'
    fi
    alias root='sudo -i'
    alias su='sudo -i'
fi

# macOS compatibility for timeout
[[ "$(uname)" == "Darwin" ]] && alias timeout=gtimeout

# Prevent catastrophic accidents on root
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Interactive safety (stops accidental overwrites)
alias cp='cp -iv'
alias ln='ln -iv'
alias mv='mv -iv'
# -I prompts once before removing more than three files
alias rm='rm -Iv --one-file-system --preserve-root'
alias rmd='rm -rfv'

# ------------------------------------------
# Navigation & Listing
# ------------------------------------------

# cd
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias ~='cd ~'
# alias c="cd" # was too annoying
alias home='cd ~'
alias cd~='cd ~'

## ls
# ls variants (Colorized)
if [[ "$(uname)" == "Darwin" ]]; then
    alias ls='ls -Gph'
else
    alias ls='ls -Fph --color=auto --group-directories-first'
fi

alias l='ls'
alias ls='ls -Gl'
alias lla='ls -Alh'
alias lsd="ls -d */" # List only directories
alias ldir="lsd"
alias ll="ls -Alh"  # show hidden files
alias la='ls -aAlh'  # same as above, but no . or ..
alias lsa="ls -la"
# alias lsd="ls -a1F | grep /$"
alias lt="la -lt"
alias l.='ls -d .* -G'  # show only hidden files
alias labc='ls -lap'  #alphabetical sort
alias lf="ls -l | egrep -v '^d'"  # files only

alias mkcd='mkdir -p $1 && cd $1'

# ------------------------------------------
# System Monitoring & Tools
# ------------------------------------------
alias c='clear'
alias cls='clear && ls'
alias clss='clear && lsa'
alias h='history'
alias x='exit'
alias v='vim'
alias vi='vim'
alias edit='vim'
alias ebrc='vim ~/.bashrc'

# Resource usage
alias df='df -H'
alias du='du -ch'
alias top='htop' # Assumes htop is installed
alias path='echo -e ${PATH//:/\\n}'
alias j='jobs -l'

# Networking
alias myip="curl -s icanhazip.com"
alias ping='ping -c 5'
alias header='curl -I'
alias ports='[[ "$(uname)" == "Darwin" ]] && netstat -tulanp || ss -tulanp'

# ------------------------------------------
# Archives (The "I always forget the flags" section)
# ------------------------------------------
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# ------------------------------------------
# Git Shortcuts
# ------------------------------------------
# Note: These assume you have these aliases defined in your .gitconfig as well
# push, pull, checkout, check -b, rename in .bash_functions
alias ga='git a'
alias gb='git b'
alias gbr='git br'
alias gbd='git branch -D'
alias gc='git cam'
alias gcl='git cl'
alias gl="git l"
alias gll="git ll"
alias grr="git rr"
alias gs='git st'
alias greset='git reset --hard HEAD'
alias gclean='git clean -f'
alias gclone='git clone'
alias gf='git fetch'
alias gfetch='git fetch'

# ------------------------------------------
# Specialized
# ------------------------------------------
alias update-node='fnm install --lts && LTS_VER=$(fnm list | grep "lts-latest" | awk "{print \$2}") && fnm default "$LTS_VER" && date +%s > "$DOTFILES_CONFIG_DIR/.node_update_timestamp" && echo "Node LTS updated to $LTS_VER"'

## TODO reorg
if [[ "$(uname)" == "Darwin" ]]; then
    alias ps='ps aux'
else
    alias ps='ps auxf'
fi

alias top='htop'
if [[ "$(uname)" == "Darwin" ]]; then
    alias top10='ps -arcwwwxo pid,comm,%cpu,%mem | head -n 11'
else
    alias top10='ps -eo pid,comm,%cpu,%mem --sort=-%cpu | head -n 11'
fi
alias uptime='uptime -p'
# alias mv='timeout 8 mv -iv'
# alias rm='timeout 3 rm -Iv --one-file-system --preserve-root'
# alias rmd='rm  --recursive --force --verbose '
# alias mkdir='mkdir -pv'

# chmod
alias mx='chmod a+x'
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'

# grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# vim
alias vi=vim
alias svi='sudo vi'
alias vis='vim "+set si"'
alias edit='vim'

# installer
alias p="sudo pacman"
alias y="yaourt"

# internet check
alias myip="curl icanhazip.com"
alias ping='ping -c 5'
alias p4="ping 4.2.2.2 -c 4"
# shortcut  for iptables and pass it via sudo#
alias ipt='sudo /sbin/iptables'
# display all rules #
alias iptlist='sudo /sbin/iptables -L -n -v --line-numbers'
alias iptlistin='sudo /sbin/iptables -L INPUT -n -v --line-numbers'
alias iptlistout='sudo /sbin/iptables -L OUTPUT -n -v --line-numbers'
alias iptlistfw='sudo /sbin/iptables -L FORWARD -n -v --line-numbers'
alias firewall=iptlist
# get web server headers #
alias header='curl -I'
# find out if remote server supports gzip / mod_deflate or not #
alias headerc='curl -I --compress'
# All of our servers eth1 is connected to the Internets via vlan / router etc  ##
alias dnstop='dnstop -l 5  eth1'
alias vnstat='vnstat -i eth1'
alias iftop='iftop -i eth1'
alias tcpdump='tcpdump -i eth1'
alias ethtool='ethtool eth1'
# work on wlan0 by default #
# Only useful for laptop as all servers are without wireless interface
alias iwconfig='iwconfig wlan0'

if [[ "$(uname)" == "Darwin" ]]; then
    alias diskspace="du | sort -n -r | more"
    alias ports='netstat -tulanp'
else
    alias diskspace="du -S | sort -n -r | more"
    alias ports='ss -tulanp'
fi

alias dmesg10='sudo dmesg | tail -n 10'
alias folder="find . -maxdepth 1 -type d -print | xargs du -sk | sort -rn"
alias path='echo -e ${PATH//:/\\n}'
alias wc='wc -l -w -c'
alias nowtime='date +"%T"'
alias nowdate='date +"%d-%m-%Y"'
alias ebrc='edit ~/.bashrc'
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'
alias mountedinfo='df -hT'

# other
alias so0="cmatrix"

# install  colordiff package
# alias diff='colordiff'
