#!/usr/bin/env bash

# ------------------------------------------
# Advanced Dircolors & LS
# ------------------------------------------
if command -v dircolors >/dev/null 2>&1; then
    if [[ -r ~/.dircolors ]]; then
        eval "$(dircolors -b ~/.dircolors)"
    else
        eval "$(dircolors -b)"
    fi

    # Standard color aliases
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias diff='diff --color=auto'
fi

# ------------------------------------------
# Lesspipe & Pager Enhancements
# ------------------------------------------
# Allows 'less' to open and view contents of archives, PDFs, etc.
if [[ -x /usr/bin/lesspipe ]]; then
    eval "$(SHELL=/bin/sh lesspipe)"
fi

# ------------------------------------------
# Debian/Chroot Detection
# ------------------------------------------
# set variable identifying the chroot you work in (used in the prompt below)
if [[ -z "${debian_chroot:-}" ]] && [[ -r /etc/debian_chroot ]]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# ------------------------------------------
# Smart CD & Directory Behavior
# ------------------------------------------
# Automatically 'ls' after every 'cd'
cd() {
    builtin cd "$@" && ls
}
